// Contas padrão para demo
export const DEMO_ACCOUNTS = {
  encarregado: {
    id: "ENC001",
    email: "maria.silva@email.ao",
    password: "enc123",
    nome: "Maria da Silva",
    alunoId: "ALU001",
    alunoNome: "João Manuel da Silva",
    alunoNumero: "2024001234",
    parentesco: "Mãe",
    telefone: "+244 912 345 678",
    foto: "/placeholder-user.jpg",
  },
  aluno: {
    id: "ALU001",
    numeroAluno: "2024001234",
    password: "aluno123",
    nome: "João Manuel da Silva",
    email: "joao.silva@aluno.ipmayombe.ao",
    curso: "Informática de Gestão",
    cursoId: "CUR002",
    turma: "IG-3A",
    turmaId: "TUR001",
    ano: 3,
    dataNascimento: "2003-05-15",
    genero: "Masculino",
    telefone: "+244 923 456 789",
    endereco: "Bairro Maianga, Luanda",
    encarregado: {
      nome: "Maria da Silva",
      telefone: "+244 912 345 678",
      email: "maria.silva@email.ao",
      parentesco: "Mãe",
    },
    foto: "/african-student.jpg",
    dataMatricula: "2022-02-15",
    estado: "Activo",
  },
  professor: {
    id: "PROF001",
    email: "maria.santos@ipmayombe.ao",
    password: "prof123",
    nome: "Profª. Maria dos Santos",
    departamento: "Ciências e Tecnologia",
    departamentoId: "DEP001",
    disciplinas: [
      { id: "DIS001", nome: "Programação Web", turmas: ["IG-3A", "IG-3B"] },
      { id: "DIS002", nome: "Base de Dados", turmas: ["IG-2A", "IG-2B"] },
      { id: "DIS003", nome: "Sistemas Operativos", turmas: ["IG-3A"] },
    ],
    telefone: "+244 934 567 890",
    formacao: "Mestrado em Engenharia Informática",
    dataContratacao: "2018-09-01",
    estado: "Activo",
    foto: "/african-professor.jpg",
  },
  admin: {
    id: "ADM001",
    email: "admin@ipmayombe.ao",
    password: "admin123",
    nome: "António Ferreira",
    cargo: "Administrador do Sistema",
    telefone: "+244 945 678 901",
    foto: "/african-administrator.jpg",
    permissoes: ["all"],
  },
}

// Anos Lectivos
export const TRIMESTRES = [
  {
    id: "TRI001",
    nome: "1º Trimestre",
    anoLectivoId: "AL001",
    inicio: "2024-09-01",
    fim: "2024-12-15",
    estado: "Encerrado",
  },
  {
    id: "TRI002",
    nome: "2º Trimestre",
    anoLectivoId: "AL001",
    inicio: "2025-01-06",
    fim: "2025-04-05",
    estado: "Activo",
  },
  {
    id: "TRI003",
    nome: "3º Trimestre",
    anoLectivoId: "AL001",
    inicio: "2025-04-21",
    fim: "2025-07-15",
    estado: "Pendente",
  },
]

// Departamentos
export const NOTAS_PENDENTES = [
  {
    id: "NOT001",
    alunoId: "ALU001",
    alunoNome: "João Manuel da Silva",
    disciplinaId: "DIS001",
    disciplinaNome: "Programação Web",
    turma: "IG-3A",
    trimestre: "2º Trimestre",
    p1: 16,
    p2: 18,
    trabalho: 17,
    exame: null,
    media: null,
    estado: "Pendente",
    professorId: "PROF001",
    professorNome: "Profª. Maria Santos",
    dataLancamento: "2025-02-10",
    observacoes: "",
  },
  {
    id: "NOT002",
    alunoId: "ALU002",
    alunoNome: "Ana Beatriz Ferreira",
    disciplinaId: "DIS001",
    disciplinaNome: "Programação Web",
    turma: "IG-3A",
    trimestre: "2º Trimestre",
    p1: 14,
    p2: 15,
    trabalho: 16,
    exame: null,
    media: null,
    estado: "Pendente",
    professorId: "PROF001",
    professorNome: "Profª. Maria Santos",
    dataLancamento: "2025-02-10",
    observacoes: "",
  },
  {
    id: "NOT003",
    alunoId: "ALU003",
    alunoNome: "Pedro Miguel Santos",
    disciplinaId: "DIS001",
    disciplinaNome: "Programação Web",
    turma: "IG-3A",
    trimestre: "2º Trimestre",
    p1: 12,
    p2: 10,
    trabalho: 13,
    exame: null,
    media: null,
    estado: "Pendente",
    professorId: "PROF001",
    professorNome: "Profª. Maria Santos",
    dataLancamento: "2025-02-10",
    observacoes: "",
  },
  {
    id: "NOT004",
    alunoId: "ALU004",
    alunoNome: "Maria José Costa",
    disciplinaId: "DIS002",
    disciplinaNome: "Base de Dados",
    turma: "IG-2B",
    trimestre: "2º Trimestre",
    p1: 18,
    p2: 19,
    trabalho: 18,
    exame: 17,
    media: 18.0,
    estado: "Aprovado",
    professorId: "PROF001",
    professorNome: "Profª. Maria Santos",
    dataLancamento: "2025-02-08",
    observacoes: "Excelente desempenho",
  },
  {
    id: "NOT005",
    alunoId: "ALU005",
    alunoNome: "Carlos Eduardo Gomes",
    disciplinaId: "DIS002",
    disciplinaNome: "Base de Dados",
    turma: "IG-2B",
    trimestre: "2º Trimestre",
    p1: 8,
    p2: 7,
    trabalho: 10,
    exame: null,
    media: null,
    estado: "Rejeitado",
    professorId: "PROF001",
    professorNome: "Profª. Maria Santos",
    dataLancamento: "2025-02-08",
    observacoes: "Verificar nota da P2 - possível erro",
  },
]

// Notas completas dos alunos
export const ALUNO_DISCIPLINAS = [
  {
    id: 1,
    nome: "Programação Web",
    professor: "Profª. Maria dos Santos",
    notas: { p1: 16, p2: 18, trabalho: 17, exame: 15 },
    media: 16.5,
    estado: "Aprovado",
    trimestre: "1º Trimestre",
  },
  {
    id: 2,
    nome: "Base de Dados",
    professor: "Prof. Carlos Mendes",
    notas: { p1: 14, p2: 15, trabalho: 16, exame: 14 },
    media: 14.75,
    estado: "Aprovado",
    trimestre: "1º Trimestre",
  },
  {
    id: 3,
    nome: "Sistemas Operativos",
    professor: "Prof. Manuel Gomes",
    notas: { p1: 12, p2: 13, trabalho: 14, exame: null },
    media: null,
    estado: "Em curso",
    trimestre: "2º Trimestre",
  },
  {
    id: 4,
    nome: "Redes de Computadores",
    professor: "Prof. Pedro Alves",
    notas: { p1: 17, p2: 16, trabalho: 18, exame: 16 },
    media: 16.75,
    estado: "Aprovado",
    trimestre: "1º Trimestre",
  },
  {
    id: 5,
    nome: "Matemática Aplicada",
    professor: "Profª. Ana Costa",
    notas: { p1: 10, p2: 11, trabalho: 12, exame: null },
    media: null,
    estado: "Em curso",
    trimestre: "2º Trimestre",
  },
  {
    id: 6,
    nome: "Inglês Técnico",
    professor: "Prof. David Sousa",
    notas: { p1: 15, p2: 16, trabalho: 17, exame: 15 },
    media: 15.75,
    estado: "Aprovado",
    trimestre: "1º Trimestre",
  },
]

// Histórico de notas anuais
export const HISTORICO_NOTAS = [
  { anoLectivo: "2022/2023", ano: 1, mediaAnual: 14.2, estado: "Aprovado", disciplinas: 8, aprovadas: 8 },
  { anoLectivo: "2023/2024", ano: 2, mediaAnual: 15.1, estado: "Aprovado", disciplinas: 8, aprovadas: 8 },
  { anoLectivo: "2024/2025", ano: 3, mediaAnual: null, estado: "Em curso", disciplinas: 6, aprovadas: 4 },
]

// Horário semanal do aluno
export const PROFESSOR_TURMAS = [
  {
    id: "TUR001",
    nome: "IG-3A",
    curso: "Informática de Gestão",
    ano: 3,
    disciplina: "Programação Web",
    totalAlunos: 28,
    mediaGeral: 14.5,
    notasPendentes: 5,
  },
  {
    id: "TUR002",
    nome: "IG-2A",
    curso: "Informática de Gestão",
    ano: 2,
    disciplina: "Base de Dados",
    totalAlunos: 26,
    mediaGeral: 13.8,
    notasPendentes: 8,
  },
  {
    id: "TUR003",
    nome: "CONT-3A",
    curso: "Contabilidade",
    ano: 3,
    disciplina: "Contabilidade Analítica",
    totalAlunos: 24,
    mediaGeral: 14.2,
    notasPendentes: 3,
  },
]

// Alunos de uma turma para lançamento de notas
export const TURMA_ALUNOS = [
  {
    id: 1,
    numero: "2024001234",
    nome: "João Manuel da Silva",
    p1: 16,
    p2: 18,
    trabalho: 17,
    exame: null,
    media: null,
    estado: "Pendente",
    foto: "/african-student.jpg",
  },
  {
    id: 2,
    numero: "2024001235",
    nome: "Ana Beatriz Ferreira",
    p1: 14,
    p2: 15,
    trabalho: 16,
    exame: null,
    media: null,
    estado: "Pendente",
    foto: "/african-female-student.jpg",
  },
  {
    id: 3,
    numero: "2024001236",
    nome: "Pedro Miguel Santos",
    p1: 12,
    p2: 10,
    trabalho: 13,
    exame: null,
    media: null,
    estado: "Pendente",
    foto: "/placeholder.svg?height=40&width=40",
  },
  {
    id: 4,
    numero: "2024001237",
    nome: "Maria José Costa",
    p1: 18,
    p2: 19,
    trabalho: 18,
    exame: 17,
    media: 18.0,
    estado: "Aprovado",
    foto: "/african-female-student-2.jpg",
  },
  {
    id: 5,
    numero: "2024001238",
    nome: "Carlos Eduardo Gomes",
    p1: 8,
    p2: 7,
    trabalho: 10,
    exame: null,
    media: null,
    estado: "Rascunho",
    foto: "/african-male-student-2.jpg",
  },
  {
    id: 6,
    numero: "2024001239",
    nome: "Luísa Helena Martins",
    p1: 15,
    p2: 16,
    trabalho: 14,
    exame: 15,
    media: 15.0,
    estado: "Aprovado",
    foto: "/african-female-student-3.jpg",
  },
  {
    id: 7,
    numero: "2024001240",
    nome: "Ricardo António Sousa",
    p1: 13,
    p2: 14,
    trabalho: 15,
    exame: 13,
    media: 13.75,
    estado: "Aprovado",
    foto: "/african-male-student-3.jpg",
  },
  {
    id: 8,
    numero: "2024001241",
    nome: "Sofia Margarida Alves",
    p1: 17,
    p2: 16,
    trabalho: 18,
    exame: 16,
    media: 16.75,
    estado: "Aprovado",
    foto: "/african-female-student-4.jpg",
  },
]

// Estatísticas gerais do admin
export const CONFIGURACOES = {
  escola: {
    nome: "Instituto Politécnico do Mayombe",
    sigla: "IPM",
    endereco: "Buco Zau, Cabinda, Angola",
    telefone: "+244 222 123 456",
    email: "geral@ipmayombe.ao",
    website: "www.ipmayombe.ao",
    logo: "/placeholder.svg?height=100&width=100",
  },
  academico: {
    mediaMinima: 10,
    pesoP1: 20,
    pesoP2: 20,
    pesoTrabalho: 20,
    pesoExame: 40,
    notaMaxima: 20,
    notaMinima: 0,
    decimais: 2,
  },
  sistema: {
    tema: "claro",
    idioma: "pt-AO",
    formatoData: "dd/MM/yyyy",
    moeda: "AOA",
  },
}

// Evolução de dados para gráficos
export const EVOLUCAO_NOTAS = [
  { mes: "Set", media: 12.5, aprovados: 78, reprovados: 22 },
  { mes: "Out", media: 13.2, aprovados: 82, reprovados: 18 },
  { mes: "Nov", media: 14.1, aprovados: 85, reprovados: 15 },
  { mes: "Dez", media: 14.8, aprovados: 87, reprovados: 13 },
  { mes: "Jan", media: 15.5, aprovados: 89, reprovados: 11 },
  { mes: "Fev", media: 15.2, aprovados: 88, reprovados: 12 },
]

export const DESEMPENHO_DISCIPLINAS = [
  { disciplina: "Prog. Web", media: 15.2, aprovados: 92 },
  { disciplina: "Base Dados", media: 14.1, aprovados: 88 },
  { disciplina: "Sist. Op.", media: 13.8, aprovados: 85 },
  { disciplina: "Redes", media: 14.5, aprovados: 87 },
  { disciplina: "Matemática", media: 12.3, aprovados: 76 },
  { disciplina: "Inglês", media: 15.8, aprovados: 94 },
]

export const COMPARATIVO_TRIMESTRES = [
  { turma: "IG-3A", t1: 14.2, t2: 15.1, t3: null },
  { turma: "IG-3B", t1: 13.8, t2: 14.5, t3: null },
  { turma: "IG-2A", t1: 14.5, t2: 14.8, t3: null },
  { turma: "EI-3A", t1: 15.2, t2: 15.6, t3: null },
  { turma: "CG-1A", t1: 13.1, t2: 13.9, t3: null },
]

// ─── Módulo 6: Financeiro ─────────────────────────────────────────────────────

